name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Enabling python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      - name: Installing python packages
        run: pip install -r requirements.txt

      - name: Generating slides
        run: ./build.sh

      - name: Upload pages directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: present

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
